// Assets
import avatar1 from "assets/img/avatars/avatar1.png";

export const tablesProjectData = [
  {
    logo: avatar1,
    name: "Imane Makroum",
    matricule: "AR52H7 ",
    lieu: "Casablanca",
    livrer: 10,
    nonLivrer: 2,
    retour: 1,
    status: "Non Connecté",
    progression: 60,
    date_connec: "21/02/2023",
    heure_connec: "10.42",
    telephone: "06 52 55 89 74",
    agence: "300",
  },
  {
    logo: avatar1,
    name: "Ismail Kardoudi",
    matricule: "AR52H77",
    lieu: "Casablanca",
    livrer: 15,
    nonLivrer: 2,
    retour: 1,
    status: "Non Connecté",
    progression: 60,
    date_connec: "21/02/2023",
    heure_connec: "10.42",
    telephone: "06 11 22 33 44",
    agence: "300",
  },
  {
    logo: "avatar2",
    name: "Mohammed Amine",
    matricule: "AB34C9",
    lieu: "Rabat",
    livrer: 7,
    nonLivrer: 4,
    retour: 2,
    status: "Connecté",
    progression: 70,
    date_connec: "",
    heure_connec: "",
    telephone: "06 55 44 33 22",
    agence: "300",
  },
  {
    logo: "avatar3",
    name: "Fatima Zahra",
    matricule: "CD56E1",
    lieu: "Marrakech",
    livrer: 5,
    nonLivrer: 5,
    retour: 3,
    status: "Non Connecté",
    progression: 50,
    telephone: "06 99 88 77 66",
    agence: "300",

    date_connec: "",
    heure_connec: "",
  },
  {
    logo: "avatar4",
    name: "Hassan El Alami",
    matricule: "EF78G3",
    lieu: "Fes",
    livrer: 9,
    nonLivrer: 3,
    retour: 1,
    status: "Connecté",
    progression: 80,
    telephone: "06 12 34 56 78",
    agence: "300",
  },
  {
    logo: "avatar5",
    name: "Omar Benchekroun",
    matricule: "GH90I5",
    lieu: "Agadir",
    livrer: 12,
    nonLivrer: 1,
    retour: 0,
    status: "Non Connecté",
    date_connec: "21/02/2023",
    heure_connec: "10.42",
    progression: 90,
    telephone: "06 55 44 33 22",
    agence: "500",
  },
  {
    logo: "avatar6",
    name: "Sara El Idrissi",
    matricule: "IJ12K7",
    lieu: "Tanger",
    livrer: 8,
    nonLivrer: 2,
    retour: 2,
    status: "Non Connecté",
    progression: 70,
    telephone: "06 12 34 56 78",
    agence: "300",
    date_connec: "",
    heure_connec: "",
  },
  {
    logo: "avatar7",
    name: "Youssef Chahbi",
    matricule: "KL14M9",
    lieu: "Tetouan",
    livrer: 6,
    nonLivrer: 4,
    retour: 3,
    status: "Non Connecté",
    progression: 60,
    agence: "100",
    telephone: "06 55 44 33 22",
  },
  {
    logo: "avatar8",
    name: "Asmaa El Hassani",
    matricule: "MN16O1",
    lieu: "Oujda",
    livrer: 11,
    nonLivrer: 1,
    retour: 1,
    status: "Non Connecté",
    progression: 90,
    telephone: "06 12 34 56 78",
    agence: "100",
  },
  {
    logo: "avatar5",
    name: "Omar Benchekroun",
    matricule: "GH90I5",
    lieu: "Agadir",
    livrer: 12,
    nonLivrer: 1,
    retour: 0,
    status: "Non Connecté",
    date_connec: "21/02/2023",
    heure_connec: "10.42",
    progression: 90,
    telephone: "06 55 44 33 22",
    agence: "500",
  },
  {
    logo: "avatar6",
    name: "Sara El Idrissi",
    matricule: "IJ12K7",
    lieu: "Tanger",
    livrer: 8,
    nonLivrer: 2,
    retour: 2,
    status: "Non Connecté",
    progression: 70,
    telephone: "06 12 34 56 78",
    agence: "300",
    date_connec: "",
    heure_connec: "",
  },
  {
    logo: "avatar7",
    name: "Youssef Chahbi",
    matricule: "KL14M9",
    lieu: "Tetouan",
    livrer: 6,
    nonLivrer: 4,
    retour: 3,
    status: "Non Connecté",
    progression: 60,
    agence: "100",
    telephone: "06 55 44 33 22",
  },
  {
    logo: "avatar8",
    name: "Asmaa El Hassani",
    matricule: "MN16O1",
    lieu: "Oujda",
    livrer: 11,
    nonLivrer: 1,
    retour: 1,
    status: "Non Connecté",
    progression: 90,
    telephone: "06 12 34 56 78",
    agence: "100",
  },
  {
    logo: "avatar5",
    name: "Omar Benchekroun",
    matricule: "GH90I5",
    lieu: "Agadir",
    livrer: 12,
    nonLivrer: 1,
    retour: 0,
    status: "Connecté",
    date_connec: "21/02/2023",
    heure_connec: "10.42",
    progression: 90,
    telephone: "06 55 44 33 22",
    agence: "500",
  },
  {
    logo: "avatar6",
    name: "Sara El Idrissi",
    matricule: "IJ12K7",
    lieu: "Tanger",
    livrer: 8,
    nonLivrer: 2,
    retour: 2,
    status: "Non Connecté",
    progression: 70,
    telephone: "06 12 34 56 78",
    agence: "300",
    date_connec: "",
    heure_connec: "",
  },
  {
    logo: "avatar7",
    name: "Youssef Chahbi",
    matricule: "KL14M9",
    lieu: "Tetouan",
    livrer: 6,
    nonLivrer: 4,
    retour: 3,
    status: "Connecté",
    progression: 60,
    agence: "100",
    telephone: "06 55 44 33 22",
  },
  {
    logo: "avatar8",
    name: "Asmaa El Hassani",
    matricule: "MN16O1",
    lieu: "Oujda",
    livrer: 11,
    nonLivrer: 1,
    retour: 1,
    status: "Non Connecté",
    progression: 90,
    telephone: "06 12 34 56 78",
    agence: "100",
  },
  {
    logo: "avatar5",
    name: "Omar Benchekroun",
    matricule: "GH90I5",
    lieu: "Agadir",
    livrer: 12,
    nonLivrer: 1,
    retour: 0,
    status: "Connecté",
    date_connec: "21/02/2023",
    heure_connec: "10.42",
    progression: 90,
    telephone: "06 55 44 33 22",
    agence: "500",
  },
  {
    logo: "avatar6",
    name: "Sara El Idrissi",
    matricule: "IJ12K7",
    lieu: "Tanger",
    livrer: 8,
    nonLivrer: 2,
    retour: 2,
    status: "Connecté",
    progression: 70,
    telephone: "06 12 34 56 78",
    agence: "300",
    date_connec: "",
    heure_connec: "",
  },
  {
    logo: "avatar7",
    name: "Youssef Chahbi",
    matricule: "KL14M9",
    lieu: "Tetouan",
    livrer: 6,
    nonLivrer: 4,
    retour: 3,
    status: "Non Connecté",
    progression: 60,
    agence: "100",
    telephone: "06 55 44 33 22",
  },
  {
    logo: "avatar8",
    name: "Asmaa El Hassani",
    matricule: "MN16O1",
    lieu: "Oujda",
    livrer: 11,
    nonLivrer: 1,
    retour: 1,
    status: "Non Connecté",
    progression: 90,
    telephone: "06 12 34 56 78",
    agence: "100",
  },
];

export const livreursList = [
  {
    nomComplet: "Mohammed Amine",
    lieu: "Rabat",
    livrer: 17,
    nonLivrer: 4,
    retour: 2,
  },
  {
    nomComplet: "Fatima Zahra",
    lieu: "Marrakech",
    livrer: 15,
    nonLivrer: 5,
    retour: 3,
  },
  {
    nomComplet: "Hassan El Alami",
    lieu: "Fes",
    livrer: 19,
    nonLivrer: 3,
    retour: 1,
  },
  {
    nomComplet: "Omar Benchekroun",
    lieu: "Agadir",
    livrer: 22,
    nonLivrer: 1,
    retour: 0,
  },
];

export const socialTraffic = [
  {
    referral: "Casablanca",
    visitors: "50",
    percentage: 60,
    color: "orange",
  },
  {
    referral: "Casablanca",
    visitors: "85",
    percentage: 70,
    color: "orange",
  },
  {
    referral: "Agadir",
    visitors: "30",
    percentage: 80,
    color: "cyan",
  },
  {
    referral: "Tanger",
    visitors: "45",
    percentage: 75,
    color: "cyan",
  },
  {
    referral: "Fes",
    visitors: "33",
    percentage: 30,
    color: "orange",
  },
];
